search_algorithm: greedy
heuristic_relaxation: unary
lift_prob: 0.66
instance_ids: null
min_length: 1
max_length: 15
timeout_seconds: 900  # 15 * 60
order: increasing
benchmark_path: /home/remote/u7899572/lifted-white-plan-domain-repair/input/benchmarks-G1
log_folder: /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/gbfs-unary relax-prec-delete lp066
log_interval: 1000000
domain_class: null
