search_algorithm: dfs
heuristic_relaxation: unary
lift_prob: 0.33
instance_ids: null
min_length: 1
max_length: 15
timeout_seconds: 900  # 15 * 60
order: increasing
benchmark_path: /home/remote/u7899572/lifted-white-plan-domain-repair/input/benchmarks-G1
log_folder: /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/dfs relax-all lp033
log_interval: 1000000
domain_class: null

# renaining:
# gbfs-unary-ff relax-all lp1
# gbfs-unary-ff relax-all lp066
# gbfs-unary-ff relax-all lp033

# dfs relax-all lp033
