search_algorithm: bfs
heuristic_relaxation: unary
lift_prob: 1.0
instance_ids: null
min_length: 1
max_length: 15
timeout_seconds: 900  # 15 * 60
order: increasing
benchmark_path: /home/remote/u7899572/lifted-white-plan-domain-repair/input/benchmarks-G1
log_folder: /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_debug/bfs exhast lp1
log_interval: 1000000
domain_class: null



# exhastive grounder test
# search_algorithm: bfs
# heuristic_relaxation: unary
# lift_prob: 1.0
# min_length: 1
# max_length: 400
# timeout_seconds: 900  # 15 * 60
# log_interval: 1000000
# order: increasing
# benchmark_path: /home/remote/u7899572/lifted-white-plan-domain-repair/input/benchmarks-G1
# # log_folder: /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/dfs relax-all lp033
# log_folder: /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_debug
# domain_class: null
# instance_ids: barman-sat11-strips__ppfile06-024-err-rate-0-1
# # instance_ids: barman-sat14-strips__pp1-11-4-15-err-rate-0-1





# ##### debug
# search_algorithm: bfs
# heuristic_relaxation: unary
# lift_prob: 1.0
# instance_ids: null
# min_length: 1
# max_length: 15
# timeout_seconds: 900  # 15 * 60
# order: increasing
# benchmark_path: /home/remote/u7899572/lifted-white-plan-domain-repair/input/test
# log_folder: /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_debug
# log_interval: 1000000
# domain_class: null

##### Astar
# search_algorithm: bfs
# heuristic_relaxation: unary
# lift_prob: 0.33
# instance_ids: depot__pp01-err-rate-0-5
# min_length: 1
# max_length: 15
# timeout_seconds: 900  # 15 * 60
# order: increasing
# benchmark_path: /home/remote/u7899572/lifted-white-plan-domain-repair/input/benchmarks-G1
# log_folder: /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_debug
# log_interval: 1000000
# domain_class: null


##### Songtuan's
# search_algorithm: bfs
# heuristic_relaxation: zeroary
# lift_prob: 0.0
# instance_ids: null
# min_length: 1
# max_length: 15000
# timeout_seconds: 900  # 15 * 60
# order: increasing
# benchmark_path: /home/remote/u7899572/lifted-white-plan-domain-repair/input/benchmarks-G1
# log_folder: /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/prob0
# log_interval: 1000000
# domain_class: null


###### MAIN
# search_algorithm: astar
# heuristic_relaxation: none
# lift_prob: 1.0
# # instance_ids: null
# instance_ids: depot__pp01-err-rate-0-5
# # instance_ids: miconic__ps1-3-err-rate-0-1
# min_length: 1
# max_length: 15
# timeout_seconds: 900  # 15 * 60
# order: increasing
# benchmark_path: /home/remote/u7899572/lifted-white-plan-domain-repair/input/benchmarks-G1
# # log_folder: /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_anu/bfs relax-all lp066
# log_folder: /home/remote/u7899572/lifted-white-plan-domain-repair/exp_logs_debug
# log_interval: 1000000
# domain_class: null




###### Supported Values
# search_algorithm: astar, bfs, greedy
# heuristic_relaxation: zeroary, null, unary


###### bfs-prob06
# search_algorithm: bfs
# heuristic_relaxation: zeroary
# lift_prob: 0.6
# instance_ids: instance_ids_small_exp_set
# # instance_ids: visitall-opt11-strips/pproblem02-full-err-rate-0-1
# min_length: 1
# max_length: 15
# timeout_seconds: 900  # 15 * 60
# order: increasing
# benchmark_path: ./input/benchmarks-G1
# log_folder: ./exp_logs/13 BFS-lifted-prob06
# log_interval: 1
# domain_class: null
# run_mode: subprocess


###### AStar
# benchmark_path: ./input/benchmarks-G1
# search_algorithm: astar
# log_folder: ./exp_logs/10
# log_interval: 1
# timeout_seconds: 900  # 15 * 60
# order: increasing
# min_length: 1
# max_length: 15
# domain_class: null
# instance_ids: instance_ids_small_exp_set
# heuristic_relaxation: zeroary
# run_mode: subprocess

###### DEBUG
# benchmark_path: ./input/benchmarks-G1
# search_algorithm: astar
# log_folder: ./exp_logs_debug
# log_interval: 1
# timeout_seconds: 900  # 15 * 60
# order: increasing
# min_length: 5
# max_length: 15
# domain_class: null
# instance_ids: mprime/pprob24-err-rate-0-3
# heuristic_relaxation: null
# run_mode: subprocess


###### MISC
# benchmark_path: ./input/benchmarks-G1
# search_algorithm: astar
# log_folder: ./exp_logs/9 AStar-full-log length1-15
# log_interval: 1
# timeout_seconds: 900  # 15 * 60
# order: increasing
# min_length: 1
# max_length: 15
# domain_class: null
# instance_ids: visitall-opt11-strips/pproblem02-full-err-rate-0-1
# heuristic_relaxation: unary
# run_mode: subprocess



####### NO relaxation
# search_algorithm: bfs
# heuristic_relaxation: zeroary
# instance_ids: instance_ids_small_exp_set
# min_length: 1
# max_length: 15
# timeout_seconds: 900  # 15 * 60
# order: increasing
# benchmark_path: ./input/benchmarks-G1
# log_folder: ./exp_logs/15 BFS-lifted-prob06-no-relaxation
# log_interval: 1
# domain_class: null
# run_mode: subprocess
# lift_prob: 0.6