benchmark_path: ./input/benchmarks-G1
search_algorithm: bfs
log_folder: ./exp_logs/8 BFS-full-log length1-15
log_interval: 1
timeout_seconds: 1800  # 30 * 60
order: increasing
min_length: 1
max_length: 15
domain_class: null
instance_ids: []
heuristic_relaxation: unary

# log_folder = Path('./exp_logs_debug')
# domain_class='blocks'
# instance_ids = load_instance_ids()
# instance_ids = ["blocks/pprobBLOCKS-6-2-err-rate-0-3"]
