###### MAIN
benchmark_path: ./input/benchmarks-G1
search_algorithm: astar
log_folder: ./exp_logs/9 AStar-full-log length1-15
log_interval: 1
timeout_seconds: 900  # 15 * 60
order: increasing
min_length: 1
max_length: 15
domain_class: null
instance_ids: []
heuristic_relaxation: unary
run_mode: subprocess



###### DEBUG
# benchmark_path: ./input/benchmarks-G1
# search_algorithm: astar
# log_folder: ./exp_logs_debug
# log_interval: 1
# timeout_seconds: 900  # 15 * 60
# order: increasing
# min_length: 5
# max_length: 15
# domain_class: null
# instance_ids: mprime/pprob27-err-rate-0-5
# heuristic_relaxation: null
# run_mode: subprocess


###### MISC
# log_folder: ./exp_logs_debug
# log_folder: ./exp_logs/8 BFS-full-log length1-15
# log_folder: ./exp_logs/9 AStar-full-log length1-15
# domain_class: blocks
# instance_ids: load_instance_ids
# instance_ids: []
# instance_ids: blocks/pprobBLOCKS-6-2-err-rate-0-3
# heuristic_relaxation: null
# heuristic_relaxation: unary
