###### MAIN
search_algorithm: bfs
heuristic_relaxation: zeroary
lift_prob: 1.0
instance_ids: null
min_length: 1
max_length: 15
timeout_seconds: 900  # 15 * 60
order: increasing
benchmark_path: ./input/benchmarks-G1
log_folder: ./exp_logs_anu/00 bfs relax-prec-delete lp1
log_interval: 1000000
domain_class: null
run_mode: mpi
